### ISSUE TITLE
High CPU% consumption

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#75] opened 2017-04-04 11:35 UTC
Even without playing anything.

Using 20170329.bcba1c1 and the problem doesn't seem to have been present precedently.

**Comment by cmdrkotori** [comment] 2017-04-05 12:01
I know my readers might be getting tired of hearing this, but it works on my machine.  Here's what htop says on my main machine while the system is idle.

![screenshot_20170405_213649](https://cloud.githubusercontent.com/assets/11322485/24703765/085ab894-1a48-11e7-84dc-841d5bb9129b.png)

The only thing that increases cpu time recently was fixing an unsightly bug, and the fix causes a slight increase when playing, not idling. (548cd70d) This was a month ago. I honestly have no clue what could be causing idle cpu usage.

What version of Qt are you using and your hardware setup? I know it works fine on 5.6.0 (main,kubuntu-backports,plasma,mesa amdgpu) and 5.8.0 (laptop,arch,plasma,mesa amdgpu).

**Comment by luigino** [comment] 2017-04-05 12:38
This is what I see:

![mpc-qt_htop](https://cloud.githubusercontent.com/assets/1450716/24705622/0eb38814-1a0d-11e7-9aa3-3938db807bf1.jpg)

Actually things seem to be even better while playing, with a "mere" 25-30% CPU consumption.
Right now I'm using Qt 5.61 plasma 5.8.6 on openSUSE Leap 42.2.

Using the intel GPU, but I could switch to nvidia binary if necessary.

**Comment by ahjolinna** [comment] 2017-04-07 19:27
you can try checking if there are any leaks or errors if you are debugging with [Valgrind](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Valgrind)

**Comment by luigino** [comment] 2017-04-07 19:55
> you can try checking if there are any leaks or errors if you are debugging with Valgrind

If only I knew what to look for.
The app doesn't hang nor segfault and valgrind produces a ton of output.

**Comment by luigino** [comment] 2017-04-07 21:26
Actually there's something interesting I've noticed: when run through gdb without arguments, mpc-qt spawns and kills threads like there's no tomorrow!

That would account for the high CPU% usage when idling, I suppose.

**Comment by cmdrkotori** [comment] 2017-04-08 11:36
I haven't touched anything thread related in months since Dec/Aug or so.

Threads in my app are only used to:
* search playlists (1 thread per playlist)
* decouple mpv from gui (1 thread per mpv instance)
* decode/present media (mpv)

That said, I was able to reproduce this in OpenSuse Leap with gcc-6.

**Comment by cmdrkotori** [comment] 2017-04-08 12:00
This can be fixed by removing pulseaudio from the system.

**Closed by cmdrkotori** 2017-04-08 12:00 UTC

**Comment by ahjolinna** [comment] 2017-04-08 12:18
removing pulseaudio isn't a solution as many things do require it by default nowdays to work...like firefox and games ...and skype/discord like apps etc..

**Comment by luigino** [comment] 2017-04-08 12:19
> This can be fixed by removing pulseaudio from the system.

 :open_mouth:
And what are people supposed to use in its stead?

**Comment by ahjolinna** [comment] 2017-04-08 13:51
@luigino : well there isn't any direct replacement for pulse ....and NO using just alsa isn't an option at all it's also retarded

**Comment by cmdrkotori** [comment] 2017-04-08 14:43
This is probably an mpv bug or a pulseaudio bug. Whatever the case, I also spotted the pulseaudio process at 48% cpu time in addition to mpc-qt's high cpu time. Removing it dropped cpu down to the usual levels.

You may have some luck by turning off timer-based scheduling for pulseaudio (add tsched=0 to the load-module module-udev-detect line in /etc/pulse/default.pa). It is interesting to note that some games under wine have crackly audio without it. I do not have this enabled on my system at the moment, so your mileage may vary. Info here: https://wiki.ubuntu.com/PulseAudio/performance and here: http://0pointer.de/blog/projects/pulse-glitch-free.html

>And what are people supposed to use in its stead?

The enlightened sound daemon. Just kidding, you should be able to get away without the pulseaudio package but keep libpulse0 installed.

**Comment by ahjolinna** [comment] 2017-04-09 17:00
I haven't personally notice this problem on openSUSE leap 42.2 (my own build) and chakraOS...I mean neither mpc-qt nor pulseaudio or mpv

**Comment by ahjolinna** [comment] 2017-04-19 00:27
@luigino : I just remember that you could try out [apulse](https://github.com/i-rinat/apulse) if it helps :D

**Comment by luigino** [comment] 2017-04-19 08:12
The problem is openal-related. If that patch is not accepted by mpv or openal support is not removed on openSUSE, a good stopgap solution is to create an /etc/openal/alsoft.conf with a drivers=alsa line.

**Comment by ahjolinna** [comment] 2017-04-20 03:38
@luigino : intresting, anyway...why are u using openal? also is in't  proprietary nowdays?

**Comment by luigino** [comment] 2017-04-20 12:46
I'm not using openal, but mpv on openSUSE is built against it, so I have to take it into account.
