### ISSUE TITLE
problems with some videos after "seeking"

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#116] opened 2017-08-17 01:35 UTC
version of mpc-qt : "commit b2fe4e9" (I'm using clang instead of gcc) and [mpv-full](https://aur.archlinux.org/packages/mpv-full)

the problem; I have few videos that I tried to "seek backwards" the video just "stops" playing even thought the status is still "playing" so I have to press stop & then play for it to start...from the beginning  ... or restart mpc-qt.

then I have some other video that gets 100% out of sync

and everything works just fine using just mpv...and the videos aren't even good quality (200-400mb)

the gdb output for first problem:
[mpc-qt-log](https://github.com/cmdrkotori/mpc-qt/files/1229871/mpc-qt.txt)

the gdb output for the 2nd problem : 
[mpc-qt-log](https://send.firefox.com/download/ebe93cb434/#Wvn9TJk_bSgopS-oer1LRg)
unfortunately the file was so big so I used [send.firefox](http://send.firefox.com/)..that means
_"The link will expire after 1 download or in 24 hours."_

if you want I can send you a copy of the videos, now when mozilla released: [send.firefox](http://send.firefox.com/) ...it's easier :D 

-------------

system spec:
```
inxi -b
System:    Host: arch-anywhere Kernel: 4.12.7-2-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.4
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4397/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 384.59
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (95.2% used)
Info:      Processes: 306 Uptime: 19:10 Memory: 7301.2/15966.7MB Client: Shell (bash) inxi: 2.3.27 
```

....now back to sleep its 04:36am ...sigh

**Comment by kah0922** [comment] 2017-08-17 02:22
I've tried seeking back on videos of multiple file types and different file sizes ranging from a couple of megs to 6 gigs and I still haven't encountered this.
I am also using the latest mpc-qt git and libmpv .26.

**Comment by cmdrkotori** [comment] 2017-08-17 02:46
I see these are avi, but all my video collections are mostly mkv. Tell me which torrent it comes from and I'll grab the example file. (I know how to download securely.) A cursory search shows torrents around 64Gb or so for the first and 34Gb or so for the second.

**Comment by ahjolinna** [comment] 2017-08-17 02:57
@cmdrkotori : well as the torrent what I used was little bit slow, just give you the send firefox link (it wont be that big (legal) problem as its just 1 download or/and expires in 24h):
link to [House MD S1 Ep09 - DNR](https://send.firefox.com/download/bac55918a8/#LSNo3tz51CurGdaKh8zToA)

currently the problem seem to affect all the house md seasons ..some in little bit different ways but everything is related to seeking backwards or at times forwards

------

most of my anime are in mkv, but some old tv shows and anime are in avi or other horrible format/container

**Comment by cmdrkotori** [comment] 2017-08-17 10:48
Hmm, I can't seem to reproduce this with stock mpv from the arch community repo. I can seek back and forth without triggering a stop, although I am using software decoding. Hardware decoding with vaapi/vdpau seems fine too.

It is strange that in the first log that mpv's pause property is toggled several times to no effect. I suspect that cuvid may be at fault. I sorry I can't completely test for this, I have a video card from a different vendor. Does the issue still happen with hwdec turned off or with mpv proper? This might be a mpv issue.

**Comment by ahjolinna** [comment] 2017-08-17 12:55
@cmdrkotori : the problem did vanish when I use software decoding, but when I tried (cuvid & vdpau) hardware decoding with basic MPV or [QMPlay2](https://github.com/zaps166/QMPlay2) the videos do play fine on them.

I also tested out mpv(-full)-git version if that would be any better as it has some cuvid fixes...but no.

the problem is only on mpc-qt......

this does remind me could you add to the settings a general "reset/restore defaults" button...why?
well as I was writing this I was think maybe I should test this out with "default settings + just enable cuvid hardware decoding" ....and it worked.

I just had to remove my "~/.config/mpc-qt/" the settings, which can be problem for some users

**Comment by ahjolinna** [comment] 2017-08-17 13:03
darn it, now when I made this "settings reset" I can't see/choose my audio device(s):
![image](https://user-images.githubusercontent.com/6993072/29413624-a61bf83c-8365-11e7-8de4-5ffd6464acbf.png)

**Comment by cmdrkotori** [comment] 2017-08-17 23:45
tbh I didn't notice that audio-devices had changed to audio-device-list.

**Comment by cmdrkotori** [comment] 2017-08-17 23:50
As noted above, I can't reproduce the exact bug to determine what to fix because of lack of cuvid-capable video card. Patches welcome.

**Comment by ahjolinna** [comment] 2017-08-18 00:13
@cmdrkotori : well like I said previously ... apparently not clearly enough...it works now after I rested all my setting (by removing "~/.config/mpc-qt/") and then I put my old settings back one by one and it still worked....maybe there was some setting I missed...but it works now.

anyway like I said before it would be nice if the was some "reset/restore defaults" for the all settings, so you don't need to "hunt" and remove   "~/.config/mpc-qt/" ...
or/and have a "debug mode" that will disable your current settings, like the[ mpv's "--no-config" option](https://mpv.io/bug-reports/)

**Comment by ahjolinna** [comment] 2017-08-18 00:44
but I think this issue can be closed as this the original issue seems to have been caused by some configuration conflict or something like that...up to you.

----

I still do have a copy of the old config folder, if you want it...[here](https://send.firefox.com/download/dcecabc741/#KdOgYs-w9fUcq5v8pSCRmQ) ...the problem did affect also vdpau not just cuvid

and the current conf folder is [here](https://send.firefox.com/download/0db59684f0/#rU0KmsHU2OkdhlpFh32x1Q) for comparison

**Comment by ahjolinna** [comment] 2017-08-21 04:05
I'm testing with basic/default settings + with "cuvid hwdec" enabled, with all codecs and with mpv-full-git (& ffmpeg-full)

-------------

when I run/debug mpc-qt with `LD_DEBUG=files mpc-qt`
I got this like hundred times when the "bug/glitch" happened ::
```
closing file=/usr/lib/libasound.so.2; direct_opencount=1
     19873:     opening file=/usr/lib/libasound.so.2 [0]; direct_opencount=2
```
and
```
sudo pacman -Qo /usr/lib/libasound.so.2
/usr/lib/libasound.so.2 is owned by alsa-lib 1.1.4.1-1
```

and found more interesting errors with: 
[strace -eopen mpc-qt.log](https://gist.github.com/ahjolinna/cd5dd135eb0bdfd6d4f2e145e238fc02) 
and with
[gdb mpc-qt core.log](https://gist.github.com/ahjolinna/46c2b8de42e5df0a20c292f00a8b788b)
there are at least few more "mpv changes"

-------

also do you need to restart mpc-qt for some of the settings to take affect?...like at least the hwdec ones, it would be nice if there was some kind of notification about this...if so.

why I ask, because as I was testing and switched between vdpau and cuvid I notice that it didn't always change...one thing that is annoying that when u change settings and press "apply" its still stays "active" like it hasn't applied them...so you arent sure if the apply or even ok button even works when u press them

**Comment by ahjolinna** [comment] 2017-08-21 11:57
I hope that helped little bit..and sorry about the messy text, I did this 3-5am.....I really should be asleep (its now 3pm) :D

**Comment by ahjolinna** [comment] 2017-08-26 00:37
@cmdrkotori : what more info do u need or is this enough?

**Comment by ahjolinna** [comment] 2017-08-27 12:33
damn I should have cheked the log I uploaded... :D -_- ...apprently gist.github didn't upload/paste everything, only half..max  because they where to big, sigh.

so I uploaded all of them to dropbox: [link](https://www.dropbox.com/s/wtufswtn9dfyc9h/mpc-qt-log.tar.gz?dl=0)

**Comment by cmdrkotori** [comment] 2018-03-30 11:56
Well since this is cuvid related the bug should eventually be fixed in mpv/ffmpeg proper, all things going well.

Anyways, I can see that this is a bug in a library or driver, so closing now.

**Closed by cmdrkotori** 2018-03-30 11:56 UTC
Labels: help wanted
