### ISSUE TITLE
Play dvd error.

### ISSUE THREAD

**Issue by zyb920** [cmdrkotori/mpc-qt#102] opened 2017-07-18 04:27 UTC
use

        QStringList list;
        list << "loadfile" << "dvd:///G:/";
        mpv::qt::command(mpv, list);

can  Solved

**Comment by cmdrkotori** [comment] 2017-07-21 07:46
Thank you. However, the problem is not knowing how to call mpv. The problem is knowing what devices are available in a _platform-independent way_. QStorageInfo provides a way to fetch storage information, but lacks device add/remove notfications, so I need to write that bit myself. I already know how to do it in linux ([cmdrkotori/udisks2](https://github.com/cmdrkotori/udisks2)), but Windows has a horribly designed window-message implementation that I'm not looking forward to touching. (devices have nothing to do with windows.)

**Comment by zyb920** [comment] 2017-07-21 07:55
on window, Get  the DVD List:

   QMap<QString, QString> _dvdMap;
    _dvdMap.clear();
    wchar_t szDrives[512];
    szDrives[0] = '\0';
    if( GetLogicalDriveStringsW( sizeof( szDrives ) - 1, szDrives ) )
    {
        wchar_t *drive = szDrives;
        UINT oldMode = SetErrorMode( SEM_FAILCRITICALERRORS );
        while( *drive )
        {
            if( GetDriveTypeW(drive) == DRIVE_CDROM )
            {
                wchar_t psz_name[512] = L"";
                GetVolumeInformationW( drive, psz_name, 511, NULL, NULL, NULL, NULL, 0 );

                char *psz_drive = FromWide( drive );
                QString displayName = psz_drive;
                char *psz_title = FromWide( psz_name );

                _dvdMap[displayName] = psz_title;

                free( psz_drive );
                free( psz_title );
            }

            /* go to next drive */
            while( *(drive++) );
        }
        SetErrorMode(oldMode);
    }

**Comment by cmdrkotori** [comment] 2018-06-01 12:53
Fixed in master.

Fix status:
* Windows: initial scan, non updating, no hotplug
* Linux: initial scan, realtime updating, hotplugging
* Mac: patches welcome

Completely reproducing functionality for windows may take a few hours to fix... perhaps two days or so to do it correctly. However it's 23:00 in kangaroo land, so not today. :ok_hand:

**Closed by cmdrkotori** 2018-06-01 12:53 UTC
