### ISSUE TITLE
[Windows] UI elements missing from latest build. 

### ISSUE THREAD

**Issue by brucethemoose** [cmdrkotori/mpc-qt#97] opened 2017-07-01 22:12 UTC
"Old" is from a build made on "Apr 24 2017 at 12:56:41". New is the latest pre-compiled windows build. All configs were reset. 

http://screenshotcomparison.com/comparison/214281

Playback controls are invisible. Also the logo is missing from the background and the options menu, changing it in options doesn't seem to help.

**Comment by brucethemoose** [comment] 2017-07-01 22:15
Also, this kind of raises another issue for the future: will the Windows releases get hotfixes if necessary?

**Comment by cmdrkotori** [comment] 2017-07-02 08:18
Is Qt5Svg.dll in the same folder?

**Comment by brucethemoose** [comment] 2017-07-02 23:47
Sorry for the late reply. Yeah, it is.

**Comment by cmdrkotori** [comment] 2017-07-04 09:08
Well the difference between the earlier build and this build is that svg were pre-rendered to png, while now they are not. I can reproduce this by renaming or removing Qt5Svg.dll.

>will the Windows releases get hotfixes if necessary?

Provided the codebase hasn't digressed too much and a new Qt version hasn't come out since then, sure.

**Comment by cmdrkotori** [comment] 2017-07-04 12:59
I can also confirm this with a non-development build of Windows, so there's that I guess. I guess a dll is missing.

**Comment by brucethemoose** [comment] 2017-07-04 15:25
Copying the whole directory to my old MPC-QT install doesn't fix it. Not sure if it would have the missing .dll or not.

**Comment by cmdrkotori** [comment] 2017-07-04 21:43
The problem is that there is a library that Qt5Svg.DLL needs that was not
copied over, that is present on a Development box but not a clean box. And
no one is getting a message that a dll is missing, but it is failing
silently. I'll likely end up looking at the Qt source code for hints or
making a static build.

**Comment by brucethemoose** [comment] 2017-07-05 00:38
I'll try setting up the environment and building it in a few hours, and see if it throws any errors.

**Comment by cmdrkotori** [comment] 2017-07-05 09:55
Fixed on the releases page.

**Closed by cmdrkotori** 2017-07-05 09:55 UTC

**Comment by cmdrkotori** [comment] 2017-07-05 10:01
For the record, the problem was that the required image format plugins were missing. The more you know.
