### ISSUE TITLE
Screenshot format not saving

### ISSUE THREAD

**Issue by drewbitt** [cmdrkotori/mpc-qt#134] opened 2017-10-01 02:24 UTC
Screenshot format does not save to png among closing / re-opening the program. Defaults back to jpg despite specifying png the last time the program ran. Screenshots to png work if you have not closed the program since changing.

V17.09 from releases (Windows)

**Comment by cmdrkotori** [comment] 2017-10-01 03:27
Duplicate of #127. Not present in master.

New release should be out soonish if I don't have a car accident today.

**Closed by cmdrkotori** 2017-10-01 03:27 UTC
