### ISSUE TITLE
Failure to Render Files on Windows after Updating to MPC-QT v17.10

### ISSUE THREAD

**Issue by ehea617** [cmdrkotori/mpc-qt#135] opened 2017-10-01 15:51 UTC
![image](https://user-images.githubusercontent.com/12926544/31056303-9114d688-a69d-11e7-8c0a-ac0661221ad7.png)

Not quite sure what is happening here. Other files don't cause a crash but just render as blue.

![image](https://user-images.githubusercontent.com/12926544/31056326-e2a24f76-a69d-11e7-9815-9474162dfc71.png)

MediaInfo of the two files:
https://gist.github.com/ehea617/e69c759e2bee842bd6534ecff8624461#file-shin-godzilla-2016-720p-bluray-flac-x264-zq-mkv-mediainfo-txt
https://gist.github.com/ehea617/e69c759e2bee842bd6534ecff8624461#file-dazzle-mp4-mediainfo-txt

**Comment by cmdrkotori** [comment] 2017-10-02 00:40
The visual c runtime is only used by youtube-dl. You could try installing [the vcruntime from microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=5555).

The blue background is typically caused by old shaders or trying to use a surface that wgl does not support.

**Comment by ehea617** [comment] 2017-10-02 01:18
I have youtube-dl added to my system path and use it frequently, so I'm pretty sure I'm not missing the vcruntime that youtube-dl requires. The blue background doesn't make much sense either, as I have been able to use MPC-QT before v17.10 just fine.

**Comment by cmdrkotori** [comment] 2017-10-02 12:49
Please upload your json settings (should be under AppData/Roaming) so I can try to reproduce this. What is your video driver btw?

Last time someone had a blue screen (#98) it was caused by stale shaders because the only reliably safe time to grab shaders tends to be straight after a mpv release. In any case we might be getting a vulkan renderer soonish with hopefully more consistent rendering across all platforms so there's hope for stuff like this.

Fair warning: I might not be able to do anything about visual c runtime errors, because my code links against mingw32 libs, not the visual c stuff.

**Comment by ehea617** [comment] 2017-10-02 12:57
Here is my driver info: https://gist.github.com/ehea617/b045f27757fec6c67e795d207d053521
Here is my settings folder: [mpc-qt.zip](https://github.com/cmdrkotori/mpc-qt/files/1348934/mpc-qt.zip)

**Comment by cmdrkotori** [comment] 2017-10-08 11:44
Just tested your settings with a random file. Sadly this works on my windows 10 vm. Does upgrading your video card driver fix it? I seem to have a newer version.

My video drivers:
```
Radeon Software Version - 17.1.1
Radeon Software Edition - Crimson ReLive
Graphics Chipset - AMD Radeon HD 7700 Series
Memory Size - 2048 MB
Memory Type - DDR3
Core Clock - 850 MHz
Windows Version - Windows 10 (64 bit)
System Memory - 8 GB
CPU Type - AMD FX(tm)-8320 Eight-Core Processor
```

The file you used will be done in about 1hr on my connection, so I'll report back soonish. Perhaps it's an obscure color conversion issue.

ˢᵒʳʳʸ ᶠᵒʳ ᵗʰᵉ ᵈᵉᶫᵃʸ, ᶦᵗ'ˢ ᵇᵉᵉᶰ ᵃ ᵇᵘˢʸ ʷᵉᵉᵏ⋅

**Comment by ehea617** [comment] 2017-10-08 15:23
I was able to fix my issue by installing a non-certified driver from AMD. Apparently, support for my particular APU was dropped. The Catalyst driver through Windows Update only includes security updates, and no new bug fixes or features. AMD released a final version of the beta Crimson driver that supports my APU, so I installed that. This fixes the issue. In anyone else has this issue, the driver you need to install is here: https://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-Software-Crimson-Edition-16.2.1-for-Non-GCN-Products-Release-Notes.aspx.

**Comment by cmdrkotori** [comment] 2017-10-09 12:15
Ok, closing as it seems to be fixed.

**Closed by cmdrkotori** 2017-10-09 12:15 UTC
