### ISSUE TITLE
Menu's renders under player when is set to "on top".

### ISSUE THREAD

**Issue by kulmegil** [cmdrkotori/mpc-qt#124] opened 2017-09-05 22:36 UTC
Most menu's renders under main window when player is in "on top" mode.

App: v17.09
OS: Windows 10 1703 

![2017-09-06 00_28_56-greenshot](https://user-images.githubusercontent.com/570575/30086257-88068ada-929a-11e7-87fa-3c2fcf867100.png)

**Comment by ahjolinna** [comment] 2017-09-05 23:45
well at least this doesn't happen for me on (arch)Linux, so this is a windows issue...can't speak of mac as I don't have one. (nor do I have windows to test this more)

**Comment by cmdrkotori** [comment] 2017-09-06 07:39
This is probably due to the way contextMenu->popup() is invoked in MainWindow::mpvw_customContextMenuRequested(). Unfortunately I'm afk until Monday next week. In the meantime, just turn always on top off.

**Comment by cmdrkotori** [comment] 2017-09-20 11:22
Actually, my first instinct about needing an extra parameter was wrong. This is a [regression in Qt](https://bugreports.qt.io/browse/QTBUG-62004) (already fixed) that should come whenever the next version of Qt is shipped by msys.

**Comment by ahjolinna** [comment] 2017-09-20 12:02
@cmdrkotori : if I remember correctly Qt5.9.2 (which has the fix) should arrive end of this month...if everything goes right that is, whenever it msys gets it I can't say but I doubt it will take that long

-----
btw. if interested [XDC 2017 Day 1 live stream](https://www.youtube.com/watch?v=g5T5wSCXkH4) starts in ~3h

**Comment by cmdrkotori** [comment] 2017-09-21 11:37
Thanks for the heads up. 👍 Unfortunately most of the conference happens when I'm asleep. :/

**Comment by ahjolinna** [comment] 2017-09-21 12:52
@cmdrkotori : it's "archived", so you can watch it afterwards when that days stream has ended.

day 2 stream, starts in ~3h: https://www.youtube.com/watch?v=F3uRpOI0xi0

from day1 stream:
for example the [Nvidia's Unix Device Memory Allocation Update](https://phoronix.com/scan.php?page=news_item&px=NVIDIA-2017-Device-Mem-API) presentation starts at [1H34min](https://youtu.be/g5T5wSCXkH4?t=1h34m48s) and the [Nvidia's HDR presentation](https://phoronix.com/scan.php?page=news_item&px=NVIDIA-HDR-XDC2017) starts at [4h37min](https://youtu.be/g5T5wSCXkH4?t=4h37m11s)

**Comment by Ilya87** [comment] 2017-11-05 11:53
Qt 5.9.2 was released Ocotober 6th. The bug should be closed?

**Comment by cmdrkotori** [comment] 2017-11-05 12:06
Yes, closing. Next release will get the fix.

**Closed by cmdrkotori** 2017-11-05 12:06 UTC
