### ISSUE TITLE
Ubuntu+KDE mpc won't compile or build

### ISSUE THREAD

**Issue by sinqbad** [cmdrkotori/mpc-qt#187] opened 2018-04-30 08:50 UTC
```
paddy@T440 mpc-qt $ sudo qmake
Info: creating stash file /src/mpc-qt/.qmake.stash

```
```
paddy@T440 mpc-qt $ make -j threads
make: *** No rule to make target 'threads'.  Stop
```

```
paddy@T440 mpc-qt $ sudo make install
/usr/lib/qt5/bin/lupdate -locations none -no-ui-lines /src/mpc-qt/mpc-qt.pro
Updating 'translations/mpc-qt_it.ts'...
    Found 829 source text(s) (0 new and 829 already existing)
Updating 'translations/mpc-qt_ru.ts'...
    Found 829 source text(s) (0 new and 829 already existing)
/usr/lib/qt5/bin/lrelease translations/mpc-qt_ru.ts -qm resources/translations/mpc-qt_ru.qm
Updating 'resources/translations/mpc-qt_ru.qm'...
    Generated 387 translation(s) (382 finished and 5 unfinished)
    Ignored 442 untranslated source text(s)
g++ -c -pipe -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o ipcmpris.o ipcmpris.cpp
In file included from ipcmpris.cpp:7:0:
mpvwidget.h:13:10: fatal error: mpv/render.h: No such file or directory
 #include <mpv/render.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:782: recipe for target 'ipcmpris.o' failed
make: *** [ipcmpris.o] Error 1
```
I'm new to linux but I followed the instructions and made sure the dependencies are installed.  This was in my root folder but I also did the same in my home directory and got the same result.

**Comment by cmdrkotori** [comment] 2018-04-30 10:49
We currently depend upon a version of mpv that is not released yet, which should be coming out real soon now.

Duplicate of #184.

**Closed by cmdrkotori** 2018-04-30 10:49 UTC

**Comment by sinqbad** [comment] 2018-05-07 13:08
```
```
pc-qt $ make -j4
/usr/lib/qt5/bin/lupdate -locations none -no-ui-lines /home/paddy/.src/mpc-qt/mpc-qt.pro
g++ -c -pipe -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o ipcmpris.o ipcmpris.cpp
g++ -c -pipe -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
g++ -c -pipe -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o mpvwidget.o mpvwidget.cpp
In file included from ipcmpris.cpp:8:0:
mpvwidget.h:13:10: fatal error: mpv/render.h: No such file or directory
 #include <mpv/render.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:782: recipe for target 'ipcmpris.o' failed
make: *** [ipcmpris.o] Error 1
make: *** Waiting for unfinished jobs....
Updating 'translations/mpc-qt_it.ts'...
    Found 839 source text(s) (0 new and 839 already existing)
Updating 'translations/mpc-qt_ru.ts'...
    Found 839 source text(s) (0 new and 839 already existing)
In file included from mainwindow.h:5:0,
                 from main.h:7,
                 from main.cpp:16:
./mpvwidget.h:13:10: fatal error: mpv/render.h: No such file or directory
 #include <mpv/render.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:804: recipe for target 'main.o' failed
make: *** [main.o] Error 1
In file included from mpvwidget.cpp:20:0:
mpvwidget.h:13:10: fatal error: mpv/render.h: No such file or directory
 #include <mpv/render.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:810: recipe for target 'mpvwidget.o' failed
make: *** [mpvwidget.o] Error 1
`
`

```

I just installed the the development version of mpv but I still get these errors.

**Comment by cmdrkotori** [comment] 2018-05-07 13:35
I just put simpler instructions in the readme. I don't think this problem is going to go away for the next two years until the next ubuntu lts.
